### PR TITLE
instructions on setting up project locally #1

### PR DESCRIPTION
**Pull request by 1-Sanchit-1**
Solving issue no #1

### CODE REVIEW

**Comment by PrerakMathur20** [comment]
Good work. But I think it would be better if the **Steps** were in a slightly smaller heading format than the Setup heading itself. Also please uncommit any or all changes made to any other file than the `README.md`.

**Comment by 1-Sanchit-1** [comment]
Hello Sir,  @PrerakMathur20  
Please Check the README,md file. 
I short the headings and uncommit all changes excet README.md file . 
Still any mistake/changes please tell ...

**Comment by PrerakMathur20** [comment]
I believe the commit wasn't either properly pushed or even committed as neither a new commit is visible on this PR nor the file is changed. Kindly look into that.

**Comment by 1-Sanchit-1** [comment]
I have rebased the branch, overwriting the last commit.

I have only these changes pushed to the branch referenced here. I couldn't see any other file than README.md changed. And have shrink he headings.

`$ git show HEAD`:

```diff
commit fe8d923948f7c271700f051c25e9a0eee962cebd
Author: 1-Sanchit-1 <lcb2021031@iiitl.ac.in>
Date:   Mon Oct 3 09:23:35 2022 +0530

    Solving #1 issue for adding a README

diff --git a/README.md b/README.md
index e5a3423..806b819 100644
--- a/README.md
+++ b/README.md
@@ -1 +1,95 @@
-# Community Platform for [Geet-Hub](https://github.com/PrerakMathur20/geet-hub-frontend)
\ No newline at end of file
+# Getting Started 
+
+These are a set of instructions to follow for you to setup the project locally and run it.
+
+# Step 1: Fork the project repository
+
+Fork the repository to you GitHub .
+
+![fork](https://user-images.githubusercontent.com/95677816/193490194-a99edc82-c7a8-4104-8108-69074f676859.png)
+
+
+# Step 2: Clone your fork
+
+Click on the code drop down menu. Now you can either download the zip file and extract it on your local system.
+
+
+![clone](https://user-images.githubusercontent.com/95677816/193492863-cd040328-ca0b-452f-9952-2c1ca40a717b.png)
+
+```bash
+git clone https://github.com/iiitl/geet-hub-community
+```
+
+# Step 3: Navigate to your local folder
+
+Since the clone was downloaded into a subdirectory of your working directory, you can navigate to it using: cd NAME_OF_REPOSITORY.
+
+```bash
+cd geet-hub-community
+```
+
+# step 4 : Install NPM packages
+
+Before running npm you should have node Js installed on your system [node install instructions](https://nodejs.org/en/download/package-manager/)
+
+```bash
+npm install
+```
+
+# Step 5: Usage
+
+```bash
+npm start
+```
+
+# Step 6: Create a new branch
+
+Use git checkout -b BRANCH_NAME to create a new branch and then immediately switch to it.
+
+```bash
+git checkout -b branch_name
+```
+
+Use git branch to show your local branches.
+  
+```bash
+git branch
+```
+
+# Step 5: Make changes in your local repository
+
+Use a text editor or IDE to make the changes you planned to the files in your local repository. Because you checked out a branch in the previous step, any edits you make will only affect that branch.
+
+# Step 6: Git Add and Commit your changes
+
+Use git add -A or git add . to stage your changes and `git commit -m "DESCRIPTION OF CHANGES"` to commit them.
+  
+ ```bash
+git add .
+git commit -m"<Description of changes>"
+```
+
+# Step 7: Push your changes to your fork
+
+When you are done making all of your changes, upload these changes to your fork using git push origin BRANCH_NAME.
+
+  ```bash
+git push origin <BRANCH_NAME>
+```
+
+# Step 9: Begin the pull request
+
+Return to your fork on GitHub, and refresh the page. You may see a highlighted area that displays your recently pushed branch.
+
+![pull-req](https://user-images.githubusercontent.com/95677816/193491384-163b1ef2-d116-4d9d-b3e5-0324b68578e5.png)
+
+# Step 10: Create the pull request
+
+Before submitting the pull request, you first need to describe the changes you made .
+
+
+![pull-req](https://user-images.githubusercontent.com/95677816/193492610-1b42d303-134b-49a8-978d-699fd61121d9.png)
+
+
+# Community Platform for [Geet-Hub](https://github.com/PrerakMathur20/geet-hub-frontend)
+
```

**Comment by PrerakMathur20** [comment]
As you yourself can see in the Changes above, the changes I've asked you to make are not even there in the HEAD. Kindly make the required changes locally and then commit those changes.

As you can see in the snippets below, the changes have not been made as asked above -

https://github.com/iiitl/geet-hub-community/blob/fe8d923948f7c271700f051c25e9a0eee962cebd/README.md?plain=1#L20

https://github.com/iiitl/geet-hub-community/blob/fe8d923948f7c271700f051c25e9a0eee962cebd/README.md?plain=1#L68

**Pull request closed without merging**
