### PR TITLE
Connected a Database

### LINKED ISSUE #2: 🗄 Connect a Database
🗄 Connect a Database
---

Using Mongo atlas database, connect a database for the project to store the data and audio file details on a server, instead of storing them locally.

**NOTE**
Once assigned, ask the maintainer for the mongo credentials to connect to the database, _DO NOT USE PERSONAL MONGO STORAGE_.

### PR DESCRIPTION
**Pull request by palashb01**
### Description:
- Resolved Package version conflicts 
- Connected MongoDB with the Backend
- Added backend with the frontend
- Connected Axios with the backend
- Removed the local storage dependency

**ScreenShot:**
 
geet3

### CODE REVIEW

**Comment by palashb01** [comment]
@PrerakMathur20  Please Review the PR, Thanks.

**Comment by PrerakMathur20** [comment]
Great Work!
Please add a working Demo with the Console's State.

Also please remove this commented code -
https://github.com/iiitl/geet-hub-community/blob/e7f2574e3fb7e9ab079f0a6a4ffd9faa78cf877f/src/components/AddContact.js#L82-L160

**Comment by palashb01** [comment]
@PrerakMathur20 Please Review my PR, Thanks.

**Comment by PrerakMathur20** [comment]
Nicely Done!
LGTM!

**Pull request merged**
