### PR TITLE
Added Dark Mode

### LINKED ISSUE #4: ⚡️Add dark mode
⚡️Add dark mode
---
Add a dark mode toggle switch in the navbar for users to toggle between the _Light_ and _Dark_ modes of the website.
Use BootStrap or MaterialUI to implement the same.

Refer - 
* [BootStrap](https://react-bootstrap.netlify.app/components/navbar/#color-schemes)
* [MaterialUI](https://mui.com/material-ui/customization/dark-mode/#dark-mode-by-default)

### PR DESCRIPTION
**Pull request by AjayMaheshwari23**
FIXES #4 
Added a button to toggle between dark and light mode . When this button is pressed it changes the classname of body tag from light-theme to dark-theme and vice versa . 
I have added corresponding colours for both the themes which creates the effect of theme changing. 
For this I made changes in App.css ,  Header.js  file . 

Attaching a video demonstrating the same : - 
https://user-images.githubusercontent.com/96301800/193445757-67866ecb-ebe1-4b38-9d5d-f933f427e6eb.mov

Screenshot 2022-10-02 at 2 14 58 PM

Screenshot 2022-10-02 at 2 15 27 PM

### CODE REVIEW

**Comment by PrerakMathur20** [comment]
Kindly add `Fixes #<Issue Number>` in your PR description to effectively link your PR to the Issue.
Moreover,do add a detailed description of your work in the description supported with a Demo/Screenshots.

**Comment by AjayMaheshwari23** [comment]
ok

**Comment by AjayMaheshwari23** [comment]
sir is it okay now ?

**Comment by PrerakMathur20** [comment]
As per the widely followed Open-Source practices, The PR title is reserved only for the mere idea of the work done in the PR, whereas the Issue is linked in the Description Box of the PR.

Also, **as previously mentioned**, add a demo video/ screenshot to support your work.

**Comment by AjayMaheshwari23** [comment]
sir I am a bit confused which one is the PR description Box , so i have updated my first comment on this PR , is that correct ? and also changed the PR name with the issue title .

**Comment by PrerakMathur20** [comment]
Yes, now it's better.

Also instead of `Dark Mode` and `Light Mode`, It would be better if you could add an icon there.
Refer -
* [Dark Theme](https://fontawesome.com/icons/moon?s=regular&f=classic) - FontAwesome
* [Light Theme](https://fontawesome.com/icons/sun?s=regular&f=classic) - FontAwesome
* [FlatIcon](https://www.flaticon.com)

There are plenty more such websites available, feel free to use any one of them.

**Comment by AjayMaheshwari23** [comment]
okay sir

**Comment by AjayMaheshwari23** [comment]
Sir I have made a commit for adding icon , so am i required to create a new pull request or this will work ?

**Comment by PrerakMathur20** [comment]
No need. Any new commits you make on your branch are directly linked to this issue. Just add the updated Screenshots or Demo for the updated work.

**Comment by AjayMaheshwari23** [comment]
FIXES #4 
Yupp Done , please review it ! 
Here's the Demo Video 

https://user-images.githubusercontent.com/96301800/193474806-348e6056-1cd6-4db7-ad58-390c52e84cc0.mov

Difference : - 
Screenshot 2022-10-03 at 1 59 50 AM

**Comment by PrerakMathur20** [comment]
LGTM!

**Pull request merged**
