### PR TITLE
Fixes #12: Resolved `maximum call stack size exceeded` error

### LINKED ISSUE #12: BUG: Add Card not working `maximum call stack exceeded`  error
### Description:

- Add Button calling the `App.js` function `add_contact` giving `maximum call stack exceeded` error.

**ScreenShots**:

geet

**Error :**

gett2

### PR DESCRIPTION
**Pull request by palashb01**
### Resolved issue #12 

**ScreenShot:**

geet3

**Description:**

- Resolved the packages conflict
- Resolved uuid function
- Add button Working

### CODE REVIEW

**Comment by palashb01** [comment]
@PrerakMathur20 Please Review my PR, Thanks.

**Comment by PrerakMathur20** [comment]
Kindly add a Working demo video with the Console's state.

**Comment by palashb01** [comment]
**Demo Video:**


https://user-images.githubusercontent.com/66828942/195253556-2ced460a-5d3d-4bde-b08b-859c4c0810e4.mp4

**Comment by palashb01** [comment]
@PrerakMathur20 Please Review my PR, Thanks.

**Comment by PrerakMathur20** [comment]
LGTM! Good work!

**Pull request merged**
